export const cinnostMap = {
  "0101": "Dělení - FORSTNER",
  "0102": "Dělení - ZAKO",
  "0103": "Dělení - Pila",
  "0201": "Stříhání - NŮŽKY HACO - 4m - bez vyložení",
  "0202": "Stříhání - NŮŽKY - 2m - H.M.T",
  "0203": "Stříhání - NŮŽKY HACO - 4m - s vyložením",
  "0204": "Střihání - HACO - kostka 90°",
  "0205": "Střihání - HACO - variabilní kostka",
  "0301": "Ohýbání - ZAKO - 6m - s dělením",
  "0302": "Ohýbání - ZAKO - 6m",
  "0303": "Ohýbání - ZAKO - 4m",
  "0304": "Ohýbání - RAS XXL",
  "0305": "Ohýbání - Ruční ohýbačka",
  "0306": "Ohýbání - Profilovačka - SCHLEBACH",
  "0307": "Ohýbání - Lis na příponky - SCHLEBACH",
  "0308": "Ohýbání - Alubender",
  "0309": "Ohýbání - Zakružovačka",
  "0401": "Ohraňování - HACO - 4m",
  "0402": "Ohraňování - HACO - 3m",
  "0501": "Vysekávání - TRUMPF 3000",
  "0502": "Vysekávání - Děrování - KINGSLAND",
  "0601": "Frézování - HAWE 3000",
  "0602": "Frézování - Aluranger",
  "0701": "Svařování - Svářečka - železo",
  "0702": "Svařování - Svářečka - Hliník",
  "0703": "Svařování - Navařování šroubů",
  "0704": "Svařování - bodovačka",
  "0801": "Ruční pracoviště - Vrtání - nýtování",
  "0802": "Ruční pracoviště - Pájení",
  "0803": "Ruční pracoviště - Kompletace",
  "0804": "Ruční pracoviště - Nakládka",
  "0805": "Ruční pracoviště - Stojanová vrtačka",
  "0901": "Balení",
  "01": "PS-Plánovaná údržba a čištění",
  "02": "PS-Přípravný čas na zakázku",
  "03": "PS-Úklid před směnou a po směně",
  "04": "PS-Přestávka na oběd",
  "05": "PS-Skládání svitků",
  "06": "PS-nakládka",
  "07": "PS-nemám práci",
  "08": "PS-porada",
  "09": "PS-organizace práce",
  "10": "PL-Dovolená",
  "11": "PL-Návštěva lékaře",
  "12": "PL-náhradní volno",
  "13": "PL-Vzorky",
  "20": "NS-Porucha stroje",
  "21": "Čekání na THP",
  "22": "NS-Živelná pohroma",
  "23": "NS-Změna technologie",
  "24": "NS-Chybějící materiál",
  "25": "NS-Storno zakázky",
  "30": "NL-Nemoc",
  "31": "NL-Pracovní úraz",
  "32": "Broušení nástrojů - Trumpf",
  "33": "PS - Čekání na materiál",
  "S-01": "Jízda",
  "S-02": "Sklad",
  "S-03": "Nakládka / Vykládka",
  "S-04": "Výroba",
  "S-05": "Úklid",
};
